# Per https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MarkEWaite
  labels:
  - dependencies
  ignore:
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - ">= 1.37.a, < 1.38"
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - ">= 1.38.a, < 1.39"
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - ">= 1.39.a, < 1.40"
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - ">= 1.40.a, < 1.41"
  - dependency-name: io.jenkins:configuration-as-code
    versions:
    - ">= 1.41.a, < 1.42"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - ">= 1.37.a, < 1.38"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - ">= 1.38.a, < 1.39"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - ">= 1.39.a, < 1.40"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - ">= 1.40.a, < 1.41"
  - dependency-name: io.jenkins.configuration-as-code:test-harness
    versions:
    - ">= 1.41.a, < 1.42"
  - dependency-name: org.jenkins-ci.plugins:trilead-api
    versions:
    - ">= 1.0.6.a, < 1.0.7"
